name: dev

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  SLACK_WEBHOOK_URL : https://hooks.slack.com/services/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 

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:

    - name : Send Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
      if: always()


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
