name: dev

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:

    - name : Send Slack Notification (Start)
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        channel: '#crime-map-app'
      if: always()

    - name : Checkout Repo  
      uses: actions/checkout@v2

         
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name : Setup Flutter    
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'

    - name: Flutter Pub get
      run : flutter pub get

    - name : Build Apk    
      run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
     
    - name: Upload Artifact To Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}       
        file: app/build/outputs/apk/release/app-release-unsigned.apk

    - name : Upload Apk To Slack
      uses: wethinkcode/github_action_slackbot@v0.1
          with:
              slack-bot-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
              slack-channel: some-channel-id
              slack-bot-function: file-upload
              slack-file: filename
              slack_optional_input_filename: file-name


    - name: Slack Notification(Complete)
      uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#crime-map-app'
        if: always()      



  