name: dev

on:

  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:

    - name : Send Slack Notification (Start)
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        channel: '#crime-map-app'
      if: always()

    - name : Checkout Repo  
      uses: actions/checkout@v2
         
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name : Setup Flutter    
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'

    - name: Flutter Pub get
      run : |
          echo  flutter clean
          echo  flutter pub get

    - name : Flutter Analyze
      run  : flutter analyze

    - name : Run Test  
      run  : flutter test

    - name : Run Test Coverage 
      run  : flutter test --coverage

    - name : Run Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        files: ./coverage/codecov.info


    - name : Build Apk    
      run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
     
    - name: Upload Artifact To Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}       
        file: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

    # - name : Upload Apk To Slack
    #   uses: adrey/slack-file-upload-action@master
    #   with:
    #     token: ${{secrets.SLACK_TOKEN}}
    #     path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
    #     channel: crime-map-app

    - name: Slack Notification(Complete)
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#crime-map-app'
      if: always()      
 